title: SYSPRO Technical Knowledge Base
logo: /assets/image/ppe_logo.png
description: This is my test on creating a GitHub pages Knowledge Base
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman